version: "3.8"

services:
  payment:
    build: ./packages/payment
    image: iot-callbot-node-payment
    ports:
      - "5000:5000"
    networks:
      - microservices-network

  usermanagement:
    build: ./packages/usermanagement
    image: iot-callbot-node-usermanagement
    ports:
      - "8000:8000"
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge
